# Generated by Django 5.1.4 on 2024-12-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_channel_channel_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='parent_id',
            field=models.IntegerField(verbose_name='parentId'),
        ),
    ]
