# Generated by Django 5.1.4 on 2024-12-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_id_alter_count_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('status', models.CharField(max_length=255, verbose_name='status')),
                ('created_date', models.DateField(blank=True, null=True)),
                ('count', models.IntegerField(verbose_name='count')),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
            },
        ),
    ]
