# Generated by Django 5.1.4 on 2024-12-25 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_relation_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='relation',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.channel'),
            preserve_default=False,
        ),
    ]
