# Generated by Django 5.1.4 on 2024-12-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_alter_relation_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='parent',
        ),
        migrations.AddField(
            model_name='relation',
            name='entity_id',
            field=models.CharField(default=1, max_length=255, verbose_name='entityId'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='parent_id',
            field=models.CharField(default=1, max_length=255, verbose_name='parentId'),
            preserve_default=False,
        ),
    ]
