# Generated by Django 5.1.4 on 2024-12-25 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_relation_entity_remove_relation_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='parent_id',
        ),
    ]
