# Generated by Django 5.1.4 on 2024-12-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_relation_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='parent_id',
            field=models.CharField(max_length=255, null=True, verbose_name='parentId'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='entity_id',
            field=models.CharField(max_length=255, null=True, verbose_name='entityId'),
        ),
    ]
