# Generated by Django 5.1.4 on 2024-12-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_relation_parent_id_alter_relation_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='entity_id',
            field=models.IntegerField(verbose_name='entityId'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='parent_id',
            field=models.IntegerField(verbose_name='parentId'),
        ),
    ]
