# Generated by Django 5.1.4 on 2024-12-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_relation_entity_id_alter_relation_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.IntegerField(verbose_name='businessId')),
                ('control_type', models.CharField(max_length=255, verbose_name='controlType')),
                ('control_id', models.IntegerField(verbose_name='controlId')),
                ('entity_id', models.IntegerField(verbose_name='entityId')),
            ],
            options={
                'verbose_name': 'control',
                'verbose_name_plural': 'controls',
            },
        ),
    ]
